apiVersion: v1
kind: Secret
metadata:
  name: yeolmu-secret
  namespace: yeolmu
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "<jdbc:mysql://.../yeolmu_market?...>"
  SPRING_DATASOURCE_USERNAME: "<rds-user>"
  SPRING_DATASOURCE_PASSWORD: "<rds-password>"
  JWT_SECRET: "<jwt-secret>"
