apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-data
  namespace: yeolmu
spec:
  storageClassName: auto-ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
