INSERT IGNORE INTO category (name, created_at, modified_at) VALUES
('디지털기기', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('생활가전', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('가구/인테리어', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('생활/주방', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('의류', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('잡화', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('도서/음반', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('스포츠/레저', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('유아동', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
('기타', UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));
